winnersData = [
    {
        edition: 1994,
        team: 'Brazil',
        goalsFor: 88,
        goalsAgainst: 42,
        win: 23,
        draw: 14,
        loss: 8,
        rankAverage: 3.4,
        rankEvolution: 5,
        semiFinals: 7,
        finals: 4,
        victories: 3
    },
    {
        edition: 1998,
        team: 'France',
        goalsFor: 54,
        goalsAgainst: 13,
        win: 19,
        draw: 8,
        loss: 2,
        rankAverage: 9.47,
        rankEvolution: 14,
        semiFinals: 3,
        finals: 0,
        victories: 0
    },
    {
        edition: 2002,
        team: 'Brazil',
        goalsFor: 115,
        goalsAgainst: 47,
        win: 33,
        draw: 10,
        loss: 13,
        rankAverage: 1.28,
        rankEvolution: -1,
        semiFinals: 9,
        finals: 6,
        victories: 4
    },
    {
        edition: 2006,
        team: 'Italy',
        goalsFor: 61,
        goalsAgainst: 26,
        win: 23,
        draw: 11,
        loss: 3,
        rankAverage: 11,
        rankEvolution: 3,
        semiFinals: 7,
        finals: 5,
        victories: 3
    },
    {
        edition: 2010,
        team: 'Spain',
        goalsFor: 101,
        goalsAgainst: 22,
        win: 40,
        draw: 3,
        loss: 1,
        rankAverage: 3.9,
        rankEvolution: 6,
        semiFinals: 1,
        finals: 0,
        victories: 0
    },
    {
        edition: 2014,
        team: 'Germany',
        goalsFor: 103,
        goalsAgainst: 54,
        win: 26,
        draw: 7,
        loss: 6,
        rankAverage: 2.5,
        rankEvolution: 1,
        semiFinals: 12,
        finals: 7,
        victories: 3
    },
    {
        edition: 2018,
        team: 'France',
        goalsFor: 76,
        goalsAgainst: 36,
        win: 26,
        draw: 5,
        loss: 7,
        rankAverage: 12.7,
        rankEvolution: 13,
        semiFinals: 5,
        finals: 2,
        victories: 1
    },
]